/home/xuejian/works/quasarLF/git/codes/lf_fit/lf_shape.py:46: RuntimeWarning: invalid value encountered in power
  return 2*p[0]/(np.power(xsi/(1+zref),p[2]) + np.power(xsi/(1+zref),p[3]))
Traceback (most recent call last):
  File "/home/xuejian/.conda/envs/customenv/lib/python2.7/site-packages/emcee/ensemble.py", line 519, in __call__
    return self.f(x, *self.args, **self.kwargs)
  File "lf_fitter.py", line 112, in lnprob
    llike = lnlike(pars)
  File "lf_fitter.py", line 104, in lnlike
    res, sigma = residual(pars)
  File "lf_fitter.py", line 94, in residual
    get_fit_data(alldata,parameters,zmins[key],zmaxs[key],key,dset_ids[key])
  File "lf_fitter.py", line 38, in get_fit_data
    L_data, PHI_data, DPHI_data = load_LF_data[dset_name](redshift)
  File "/home/xuejian/works/quasarLF/git/codes/obdata/new_load_gilkman11_lf_data.py", line 11, in load_gilkman11_lf_data
    'left', 'right', 'log_phi', 'uperr', 'lowerr', 'nqso', 'Veff', 'P'])
  File "/home/xuejian/.conda/envs/customenv/lib/python2.7/site-packages/numpy/lib/npyio.py", line 1689, in genfromtxt
    fhd = iter(np.lib._datasource.open(fname, 'rt', encoding=encoding))
  File "/home/xuejian/.conda/envs/customenv/lib/python2.7/site-packages/numpy/lib/_datasource.py", line 260, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "/home/xuejian/.conda/envs/customenv/lib/python2.7/site-packages/numpy/lib/_datasource.py", line 614, in open
    encoding=encoding, newline=newline)
MemoryError
Traceback (most recent call last):
  File "lf_fitter.py", line 129, in <module>
    pool.wait()
  File "/home/xuejian/.conda/envs/customenv/lib/python2.7/site-packages/emcee/mpi_pool.py", line 117, in wait
    result = self.function(task)
  File "/home/xuejian/.conda/envs/customenv/lib/python2.7/site-packages/emcee/ensemble.py", line 519, in __call__
    return self.f(x, *self.args, **self.kwargs)
  File "lf_fitter.py", line 112, in lnprob
    llike = lnlike(pars)
  File "lf_fitter.py", line 104, in lnlike
    res, sigma = residual(pars)
  File "lf_fitter.py", line 94, in residual
    get_fit_data(alldata,parameters,zmins[key],zmaxs[key],key,dset_ids[key])
  File "lf_fitter.py", line 38, in get_fit_data
    L_data, PHI_data, DPHI_data = load_LF_data[dset_name](redshift)
  File "/home/xuejian/works/quasarLF/git/codes/obdata/new_load_gilkman11_lf_data.py", line 11, in load_gilkman11_lf_data
    'left', 'right', 'log_phi', 'uperr', 'lowerr', 'nqso', 'Veff', 'P'])
  File "/home/xuejian/.conda/envs/customenv/lib/python2.7/site-packages/numpy/lib/npyio.py", line 1689, in genfromtxt
    fhd = iter(np.lib._datasource.open(fname, 'rt', encoding=encoding))
  File "/home/xuejian/.conda/envs/customenv/lib/python2.7/site-packages/numpy/lib/_datasource.py", line 260, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "/home/xuejian/.conda/envs/customenv/lib/python2.7/site-packages/numpy/lib/_datasource.py", line 614, in open
    encoding=encoding, newline=newline)
MemoryError
Traceback (most recent call last):
Traceback (most recent call last):
  File "/home/xuejian/.conda/envs/customenv/lib/python2.7/site-packages/emcee/ensemble.py", line 519, in __call__
Traceback (most recent call last):
  File "/home/xuejian/.conda/envs/customenv/lib/python2.7/site-packages/emcee/ensemble.py", line 519, in __call__
    return self.f(x, *self.args, **self.kwargs)
  File "lf_fitter.py", line 112, in lnprob
    llike = lnlike(pars)
  File "lf_fitter.py", line 104, in lnlike
    res, sigma = residual(pars)
  File "lf_fitter.py", line 94, in residual
    get_fit_data(alldata,parameters,zmins[key],zmaxs[key],key,dset_ids[key])
  File "lf_fitter.py", line 38, in get_fit_data
    L_data, PHI_data, DPHI_data = load_LF_data[dset_name](redshift)
  File "/home/xuejian/works/quasarLF/git/codes/obdata/new_load_gilkman11_lf_data.py", line 11, in load_gilkman11_lf_data
    'left', 'right', 'log_phi', 'uperr', 'lowerr', 'nqso', 'Veff', 'P'])
  File "/home/xuejian/.conda/envs/customenv/lib/python2.7/site-packages/numpy/lib/npyio.py", line 1689, in genfromtxt
    fhd = iter(np.lib._datasource.open(fname, 'rt', encoding=encoding))
  File "/home/xuejian/.conda/envs/customenv/lib/python2.7/site-packages/numpy/lib/_datasource.py", line 260, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "/home/xuejian/.conda/envs/customenv/lib/python2.7/site-packages/numpy/lib/_datasource.py", line 614, in open
    encoding=encoding, newline=newline)
MemoryError
Traceback (most recent call last):
  File "lf_fitter.py", line 129, in <module>
    pool.wait()
  File "/home/xuejian/.conda/envs/customenv/lib/python2.7/site-packages/emcee/mpi_pool.py", line 117, in wait
    result = self.function(task)
  File "/home/xuejian/.conda/envs/customenv/lib/python2.7/site-packages/emcee/ensemble.py", line 519, in __call__
    return self.f(x, *self.args, **self.kwargs)
  File "lf_fitter.py", line 112, in lnprob
    llike = lnlike(pars)
  File "lf_fitter.py", line 104, in lnlike
    res, sigma = residual(pars)
  File "lf_fitter.py", line 94, in residual
    get_fit_data(alldata,parameters,zmins[key],zmaxs[key],key,dset_ids[key])
  File "lf_fitter.py", line 38, in get_fit_data
    L_data, PHI_data, DPHI_data = load_LF_data[dset_name](redshift)
  File "/home/xuejian/works/quasarLF/git/codes/obdata/new_load_gilkman11_lf_data.py", line 11, in load_gilkman11_lf_data
    'left', 'right', 'log_phi', 'uperr', 'lowerr', 'nqso', 'Veff', 'P'])
  File "/home/xuejian/.conda/envs/customenv/lib/python2.7/site-packages/numpy/lib/npyio.py", line 1689, in genfromtxt
    fhd = iter(np.lib._datasource.open(fname, 'rt', encoding=encoding))
  File "/home/xuejian/.conda/envs/customenv/lib/python2.7/site-packages/numpy/lib/_datasource.py", line 260, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "/home/xuejian/.conda/envs/customenv/lib/python2.7/site-packages/numpy/lib/_datasource.py", line 614, in open
    encoding=encoding, newline=newline)
MemoryError
Traceback (most recent call last):
  File "/home/xuejian/.conda/envs/customenv/lib/python2.7/site-packages/emcee/ensemble.py", line 519, in __call__
    return self.f(x, *self.args, **self.kwargs)
  File "lf_fitter.py", line 112, in lnprob
    llike = lnlike(pars)
  File "lf_fitter.py", line 104, in lnlike
    res, sigma = residual(pars)
  File "lf_fitter.py", line 94, in residual
    get_fit_data(alldata,parameters,zmins[key],zmaxs[key],key,dset_ids[key])
  File "lf_fitter.py", line 38, in get_fit_data
    L_data, PHI_data, DPHI_data = load_LF_data[dset_name](redshift)
  File "/home/xuejian/works/quasarLF/git/codes/obdata/new_load_gilkman11_lf_data.py", line 11, in load_gilkman11_lf_data
    'left', 'right', 'log_phi', 'uperr', 'lowerr', 'nqso', 'Veff', 'P'])
  File "/home/xuejian/.conda/envs/customenv/lib/python2.7/site-packages/numpy/lib/npyio.py", line 1689, in genfromtxt
    fhd = iter(np.lib._datasource.open(fname, 'rt', encoding=encoding))
  File "/home/xuejian/.conda/envs/customenv/lib/python2.7/site-packages/numpy/lib/_datasource.py", line 260, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "/home/xuejian/.conda/envs/customenv/lib/python2.7/site-packages/numpy/lib/_datasource.py", line 614, in open
    encoding=encoding, newline=newline)
MemoryError
Traceback (most recent call last):
  File "lf_fitter.py", line 129, in <module>
    pool.wait()
  File "/home/xuejian/.conda/envs/customenv/lib/python2.7/site-packages/emcee/mpi_pool.py", line 117, in wait
    result = self.function(task)
  File "/home/xuejian/.conda/envs/customenv/lib/python2.7/site-packages/emcee/ensemble.py", line 519, in __call__
    return self.f(x, *self.args, **self.kwargs)
  File "lf_fitter.py", line 112, in lnprob
    llike = lnlike(pars)
  File "lf_fitter.py", line 104, in lnlike
    res, sigma = residual(pars)
  File "lf_fitter.py", line 94, in residual
    get_fit_data(alldata,parameters,zmins[key],zmaxs[key],key,dset_ids[key])
  File "lf_fitter.py", line 38, in get_fit_data
    L_data, PHI_data, DPHI_data = load_LF_data[dset_name](redshift)
  File "/home/xuejian/works/quasarLF/git/codes/obdata/new_load_gilkman11_lf_data.py", line 11, in load_gilkman11_lf_data
    'left', 'right', 'log_phi', 'uperr', 'lowerr', 'nqso', 'Veff', 'P'])
  File "/home/xuejian/.conda/envs/customenv/lib/python2.7/site-packages/numpy/lib/npyio.py", line 1689, in genfromtxt
    fhd = iter(np.lib._datasource.open(fname, 'rt', encoding=encoding))
  File "/home/xuejian/.conda/envs/customenv/lib/python2.7/site-packages/numpy/lib/_datasource.py", line 260, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "/home/xuejian/.conda/envs/customenv/lib/python2.7/site-packages/numpy/lib/_datasource.py", line 614, in open
    encoding=encoding, newline=newline)
MemoryError
Traceback (most recent call last):
  File "/home/xuejian/.conda/envs/customenv/lib/python2.7/site-packages/emcee/ensemble.py", line 519, in __call__
    return self.f(x, *self.args, **self.kwargs)
  File "lf_fitter.py", line 112, in lnprob
    llike = lnlike(pars)
  File "lf_fitter.py", line 104, in lnlike
    res, sigma = residual(pars)
  File "lf_fitter.py", line 94, in residual
    get_fit_data(alldata,parameters,zmins[key],zmaxs[key],key,dset_ids[key])
  File "lf_fitter.py", line 38, in get_fit_data
    L_data, PHI_data, DPHI_data = load_LF_data[dset_name](redshift)
  File "/home/xuejian/works/quasarLF/git/codes/obdata/new_load_gilkman11_lf_data.py", line 11, in load_gilkman11_lf_data
    'left', 'right', 'log_phi', 'uperr', 'lowerr', 'nqso', 'Veff', 'P'])
  File "/home/xuejian/.conda/envs/customenv/lib/python2.7/site-packages/numpy/lib/npyio.py", line 1689, in genfromtxt
    fhd = iter(np.lib._datasource.open(fname, 'rt', encoding=encoding))
  File "/home/xuejian/.conda/envs/customenv/lib/python2.7/site-packages/numpy/lib/_datasource.py", line 260, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "/home/xuejian/.conda/envs/customenv/lib/python2.7/site-packages/numpy/lib/_datasource.py", line 614, in open
    encoding=encoding, newline=newline)
MemoryError
Traceback (most recent call last):
  File "/home/xuejian/.conda/envs/customenv/lib/python2.7/site-packages/emcee/ensemble.py", line 519, in __call__
    return self.f(x, *self.args, **self.kwargs)
  File "lf_fitter.py", line 112, in lnprob
    llike = lnlike(pars)
  File "lf_fitter.py", line 104, in lnlike
    res, sigma = residual(pars)
  File "lf_fitter.py", line 94, in residual
    get_fit_data(alldata,parameters,zmins[key],zmaxs[key],key,dset_ids[key])
  File "lf_fitter.py", line 38, in get_fit_data
    L_data, PHI_data, DPHI_data = load_LF_data[dset_name](redshift)
  File "/home/xuejian/works/quasarLF/git/codes/obdata/new_load_gilkman11_lf_data.py", line 11, in load_gilkman11_lf_data
    'left', 'right', 'log_phi', 'uperr', 'lowerr', 'nqso', 'Veff', 'P'])
  File "/home/xuejian/.conda/envs/customenv/lib/python2.7/site-packages/numpy/lib/npyio.py", line 1689, in genfromtxt
    fhd = iter(np.lib._datasource.open(fname, 'rt', encoding=encoding))
  File "/home/xuejian/.conda/envs/customenv/lib/python2.7/site-packages/numpy/lib/_datasource.py", line 260, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "/home/xuejian/.conda/envs/customenv/lib/python2.7/site-packages/numpy/lib/_datasource.py", line 614, in open
    encoding=encoding, newline=newline)
MemoryError
Traceback (most recent call last):
  File "lf_fitter.py", line 129, in <module>
    pool.wait()
  File "/home/xuejian/.conda/envs/customenv/lib/python2.7/site-packages/emcee/mpi_pool.py", line 117, in wait
    result = self.function(task)
  File "/home/xuejian/.conda/envs/customenv/lib/python2.7/site-packages/emcee/ensemble.py", line 519, in __call__
    return self.f(x, *self.args, **self.kwargs)
  File "lf_fitter.py", line 112, in lnprob
    llike = lnlike(pars)
  File "lf_fitter.py", line 104, in lnlike
    res, sigma = residual(pars)
  File "lf_fitter.py", line 94, in residual
    get_fit_data(alldata,parameters,zmins[key],zmaxs[key],key,dset_ids[key])
  File "lf_fitter.py", line 38, in get_fit_data
    L_data, PHI_data, DPHI_data = load_LF_data[dset_name](redshift)
  File "/home/xuejian/works/quasarLF/git/codes/obdata/new_load_gilkman11_lf_data.py", line 11, in load_gilkman11_lf_data
    'left', 'right', 'log_phi', 'uperr', 'lowerr', 'nqso', 'Veff', 'P'])
  File "/home/xuejian/.conda/envs/customenv/lib/python2.7/site-packages/numpy/lib/npyio.py", line 1689, in genfromtxt
    fhd = iter(np.lib._datasource.open(fname, 'rt', encoding=encoding))
  File "/home/xuejian/.conda/envs/customenv/lib/python2.7/site-packages/numpy/lib/_datasource.py", line 260, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "/home/xuejian/.conda/envs/customenv/lib/python2.7/site-packages/numpy/lib/_datasource.py", line 614, in open
    encoding=encoding, newline=newline)
MemoryError
Traceback (most recent call last):
  File "/home/xuejian/.conda/envs/customenv/lib/python2.7/site-packages/emcee/ensemble.py", line 519, in __call__
    return self.f(x, *self.args, **self.kwargs)
  File "lf_fitter.py", line 112, in lnprob
    llike = lnlike(pars)
  File "lf_fitter.py", line 104, in lnlike
    res, sigma = residual(pars)
  File "lf_fitter.py", line 94, in residual
    get_fit_data(alldata,parameters,zmins[key],zmaxs[key],key,dset_ids[key])
  File "lf_fitter.py", line 38, in get_fit_data
    L_data, PHI_data, DPHI_data = load_LF_data[dset_name](redshift)
  File "/home/xuejian/works/quasarLF/git/codes/obdata/new_load_gilkman11_lf_data.py", line 11, in load_gilkman11_lf_data
    'left', 'right', 'log_phi', 'uperr', 'lowerr', 'nqso', 'Veff', 'P'])
  File "/home/xuejian/.conda/envs/customenv/lib/python2.7/site-packages/numpy/lib/npyio.py", line 1689, in genfromtxt
    fhd = iter(np.lib._datasource.open(fname, 'rt', encoding=encoding))
  File "/home/xuejian/.conda/envs/customenv/lib/python2.7/site-packages/numpy/lib/_datasource.py", line 260, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "/home/xuejian/.conda/envs/customenv/lib/python2.7/site-packages/numpy/lib/_datasource.py", line 614, in open
    encoding=encoding, newline=newline)
MemoryError
Traceback (most recent call last):
  File "lf_fitter.py", line 129, in <module>
    pool.wait()
  File "/home/xuejian/.conda/envs/customenv/lib/python2.7/site-packages/emcee/mpi_pool.py", line 117, in wait
    result = self.function(task)
  File "/home/xuejian/.conda/envs/customenv/lib/python2.7/site-packages/emcee/ensemble.py", line 519, in __call__
    return self.f(x, *self.args, **self.kwargs)
  File "lf_fitter.py", line 112, in lnprob
    llike = lnlike(pars)
  File "lf_fitter.py", line 104, in lnlike
    res, sigma = residual(pars)
  File "lf_fitter.py", line 94, in residual
    get_fit_data(alldata,parameters,zmins[key],zmaxs[key],key,dset_ids[key])
  File "lf_fitter.py", line 38, in get_fit_data
    L_data, PHI_data, DPHI_data = load_LF_data[dset_name](redshift)
  File "/home/xuejian/works/quasarLF/git/codes/obdata/new_load_gilkman11_lf_data.py", line 11, in load_gilkman11_lf_data
    'left', 'right', 'log_phi', 'uperr', 'lowerr', 'nqso', 'Veff', 'P'])
  File "/home/xuejian/.conda/envs/customenv/lib/python2.7/site-packages/numpy/lib/npyio.py", line 1689, in genfromtxt
    fhd = iter(np.lib._datasource.open(fname, 'rt', encoding=encoding))
  File "/home/xuejian/.conda/envs/customenv/lib/python2.7/site-packages/numpy/lib/_datasource.py", line 260, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "/home/xuejian/.conda/envs/customenv/lib/python2.7/site-packages/numpy/lib/_datasource.py", line 614, in open
    encoding=encoding, newline=newline)
MemoryError
Traceback (most recent call last):
  File "/home/xuejian/.conda/envs/customenv/lib/python2.7/site-packages/emcee/ensemble.py", line 519, in __call__
    return self.f(x, *self.args, **self.kwargs)
  File "lf_fitter.py", line 112, in lnprob
    llike = lnlike(pars)
  File "lf_fitter.py", line 104, in lnlike
    res, sigma = residual(pars)
  File "lf_fitter.py", line 94, in residual
    get_fit_data(alldata,parameters,zmins[key],zmaxs[key],key,dset_ids[key])
  File "lf_fitter.py", line 38, in get_fit_data
    L_data, PHI_data, DPHI_data = load_LF_data[dset_name](redshift)
  File "/home/xuejian/works/quasarLF/git/codes/obdata/new_load_gilkman11_lf_data.py", line 11, in load_gilkman11_lf_data
    'left', 'right', 'log_phi', 'uperr', 'lowerr', 'nqso', 'Veff', 'P'])
  File "/home/xuejian/.conda/envs/customenv/lib/python2.7/site-packages/numpy/lib/npyio.py", line 1689, in genfromtxt
    fhd = iter(np.lib._datasource.open(fname, 'rt', encoding=encoding))
  File "/home/xuejian/.conda/envs/customenv/lib/python2.7/site-packages/numpy/lib/_datasource.py", line 260, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "/home/xuejian/.conda/envs/customenv/lib/python2.7/site-packages/numpy/lib/_datasource.py", line 614, in open
    encoding=encoding, newline=newline)
MemoryError
Traceback (most recent call last):
  File "lf_fitter.py", line 129, in <module>
    pool.wait()
  File "/home/xuejian/.conda/envs/customenv/lib/python2.7/site-packages/emcee/mpi_pool.py", line 117, in wait
    result = self.function(task)
  File "/home/xuejian/.conda/envs/customenv/lib/python2.7/site-packages/emcee/ensemble.py", line 519, in __call__
    return self.f(x, *self.args, **self.kwargs)
  File "lf_fitter.py", line 112, in lnprob
    llike = lnlike(pars)
  File "lf_fitter.py", line 104, in lnlike
    res, sigma = residual(pars)
  File "lf_fitter.py", line 94, in residual
    get_fit_data(alldata,parameters,zmins[key],zmaxs[key],key,dset_ids[key])
  File "lf_fitter.py", line 38, in get_fit_data
    L_data, PHI_data, DPHI_data = load_LF_data[dset_name](redshift)
  File "/home/xuejian/works/quasarLF/git/codes/obdata/new_load_gilkman11_lf_data.py", line 11, in load_gilkman11_lf_data
    'left', 'right', 'log_phi', 'uperr', 'lowerr', 'nqso', 'Veff', 'P'])
  File "/home/xuejian/.conda/envs/customenv/lib/python2.7/site-packages/numpy/lib/npyio.py", line 1689, in genfromtxt
    fhd = iter(np.lib._datasource.open(fname, 'rt', encoding=encoding))
  File "/home/xuejian/.conda/envs/customenv/lib/python2.7/site-packages/numpy/lib/_datasource.py", line 260, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "/home/xuejian/.conda/envs/customenv/lib/python2.7/site-packages/numpy/lib/_datasource.py", line 614, in open
    encoding=encoding, newline=newline)
MemoryError
    return self.f(x, *self.args, **self.kwargs)
  File "lf_fitter.py", line 112, in lnprob
    llike = lnlike(pars)
  File "lf_fitter.py", line 104, in lnlike
    res, sigma = residual(pars)
  File "lf_fitter.py", line 94, in residual
    get_fit_data(alldata,parameters,zmins[key],zmaxs[key],key,dset_ids[key])
  File "lf_fitter.py", line 38, in get_fit_data
    L_data, PHI_data, DPHI_data = load_LF_data[dset_name](redshift)
  File "/home/xuejian/works/quasarLF/git/codes/obdata/new_load_gilkman11_lf_data.py", line 11, in load_gilkman11_lf_data
    'left', 'right', 'log_phi', 'uperr', 'lowerr', 'nqso', 'Veff', 'P'])
  File "/home/xuejian/.conda/envs/customenv/lib/python2.7/site-packages/numpy/lib/npyio.py", line 1689, in genfromtxt
    fhd = iter(np.lib._datasource.open(fname, 'rt', encoding=encoding))
  File "/home/xuejian/.conda/envs/customenv/lib/python2.7/site-packages/numpy/lib/_datasource.py", line 260, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "/home/xuejian/.conda/envs/customenv/lib/python2.7/site-packages/numpy/lib/_datasource.py", line 614, in open
    encoding=encoding, newline=newline)
MemoryError
  File "/home/xuejian/.conda/envs/customenv/lib/python2.7/site-packages/emcee/ensemble.py", line 519, in __call__
    return self.f(x, *self.args, **self.kwargs)
  File "lf_fitter.py", line 112, in lnprob
    llike = lnlike(pars)
  File "lf_fitter.py", line 104, in lnlike
    res, sigma = residual(pars)
  File "lf_fitter.py", line 94, in residual
    get_fit_data(alldata,parameters,zmins[key],zmaxs[key],key,dset_ids[key])
  File "lf_fitter.py", line 38, in get_fit_data
    L_data, PHI_data, DPHI_data = load_LF_data[dset_name](redshift)
  File "/home/xuejian/works/quasarLF/git/codes/obdata/new_load_gilkman11_lf_data.py", line 11, in load_gilkman11_lf_data
    'left', 'right', 'log_phi', 'uperr', 'lowerr', 'nqso', 'Veff', 'P'])
  File "/home/xuejian/.conda/envs/customenv/lib/python2.7/site-packages/numpy/lib/npyio.py", line 1689, in genfromtxt
    fhd = iter(np.lib._datasource.open(fname, 'rt', encoding=encoding))
  File "/home/xuejian/.conda/envs/customenv/lib/python2.7/site-packages/numpy/lib/_datasource.py", line 260, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "/home/xuejian/.conda/envs/customenv/lib/python2.7/site-packages/numpy/lib/_datasource.py", line 614, in open
    encoding=encoding, newline=newline)
MemoryError
Traceback (most recent call last):
  File "lf_fitter.py", line 129, in <module>
    pool.wait()
  File "/home/xuejian/.conda/envs/customenv/lib/python2.7/site-packages/emcee/mpi_pool.py", line 117, in wait
    result = self.function(task)
  File "/home/xuejian/.conda/envs/customenv/lib/python2.7/site-packages/emcee/ensemble.py", line 519, in __call__
    return self.f(x, *self.args, **self.kwargs)
  File "lf_fitter.py", line 112, in lnprob
    llike = lnlike(pars)
  File "lf_fitter.py", line 104, in lnlike
    res, sigma = residual(pars)
  File "lf_fitter.py", line 94, in residual
    get_fit_data(alldata,parameters,zmins[key],zmaxs[key],key,dset_ids[key])
  File "lf_fitter.py", line 38, in get_fit_data
    L_data, PHI_data, DPHI_data = load_LF_data[dset_name](redshift)
  File "/home/xuejian/works/quasarLF/git/codes/obdata/new_load_gilkman11_lf_data.py", line 11, in load_gilkman11_lf_data
    'left', 'right', 'log_phi', 'uperr', 'lowerr', 'nqso', 'Veff', 'P'])
  File "/home/xuejian/.conda/envs/customenv/lib/python2.7/site-packages/numpy/lib/npyio.py", line 1689, in genfromtxt
    fhd = iter(np.lib._datasource.open(fname, 'rt', encoding=encoding))
  File "/home/xuejian/.conda/envs/customenv/lib/python2.7/site-packages/numpy/lib/_datasource.py", line 260, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "/home/xuejian/.conda/envs/customenv/lib/python2.7/site-packages/numpy/lib/_datasource.py", line 614, in open
    encoding=encoding, newline=newline)
MemoryError
Traceback (most recent call last):
  File "lf_fitter.py", line 129, in <module>
    pool.wait()
  File "/home/xuejian/.conda/envs/customenv/lib/python2.7/site-packages/emcee/mpi_pool.py", line 117, in wait
    result = self.function(task)
  File "/home/xuejian/.conda/envs/customenv/lib/python2.7/site-packages/emcee/ensemble.py", line 519, in __call__
    return self.f(x, *self.args, **self.kwargs)
  File "lf_fitter.py", line 112, in lnprob
    llike = lnlike(pars)
  File "lf_fitter.py", line 104, in lnlike
    res, sigma = residual(pars)
  File "lf_fitter.py", line 94, in residual
    get_fit_data(alldata,parameters,zmins[key],zmaxs[key],key,dset_ids[key])
  File "lf_fitter.py", line 38, in get_fit_data
    L_data, PHI_data, DPHI_data = load_LF_data[dset_name](redshift)
  File "/home/xuejian/works/quasarLF/git/codes/obdata/new_load_gilkman11_lf_data.py", line 11, in load_gilkman11_lf_data
    'left', 'right', 'log_phi', 'uperr', 'lowerr', 'nqso', 'Veff', 'P'])
  File "/home/xuejian/.conda/envs/customenv/lib/python2.7/site-packages/numpy/lib/npyio.py", line 1689, in genfromtxt
    fhd = iter(np.lib._datasource.open(fname, 'rt', encoding=encoding))
  File "/home/xuejian/.conda/envs/customenv/lib/python2.7/site-packages/numpy/lib/_datasource.py", line 260, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "/home/xuejian/.conda/envs/customenv/lib/python2.7/site-packages/numpy/lib/_datasource.py", line 614, in open
    encoding=encoding, newline=newline)
MemoryError
Traceback (most recent call last):
  File "lf_fitter.py", line 129, in <module>
    pool.wait()
  File "/home/xuejian/.conda/envs/customenv/lib/python2.7/site-packages/emcee/mpi_pool.py", line 117, in wait
    result = self.function(task)
  File "/home/xuejian/.conda/envs/customenv/lib/python2.7/site-packages/emcee/ensemble.py", line 519, in __call__
    return self.f(x, *self.args, **self.kwargs)
  File "lf_fitter.py", line 112, in lnprob
    llike = lnlike(pars)
  File "lf_fitter.py", line 104, in lnlike
    res, sigma = residual(pars)
  File "lf_fitter.py", line 94, in residual
    get_fit_data(alldata,parameters,zmins[key],zmaxs[key],key,dset_ids[key])
  File "lf_fitter.py", line 38, in get_fit_data
    L_data, PHI_data, DPHI_data = load_LF_data[dset_name](redshift)
  File "/home/xuejian/works/quasarLF/git/codes/obdata/new_load_gilkman11_lf_data.py", line 11, in load_gilkman11_lf_data
    'left', 'right', 'log_phi', 'uperr', 'lowerr', 'nqso', 'Veff', 'P'])
  File "/home/xuejian/.conda/envs/customenv/lib/python2.7/site-packages/numpy/lib/npyio.py", line 1689, in genfromtxt
    fhd = iter(np.lib._datasource.open(fname, 'rt', encoding=encoding))
  File "/home/xuejian/.conda/envs/customenv/lib/python2.7/site-packages/numpy/lib/_datasource.py", line 260, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "/home/xuejian/.conda/envs/customenv/lib/python2.7/site-packages/numpy/lib/_datasource.py", line 614, in open
    encoding=encoding, newline=newline)
MemoryError
Traceback (most recent call last):
  File "/home/xuejian/.conda/envs/customenv/lib/python2.7/site-packages/emcee/ensemble.py", line 519, in __call__
    return self.f(x, *self.args, **self.kwargs)
  File "lf_fitter.py", line 112, in lnprob
    llike = lnlike(pars)
  File "lf_fitter.py", line 104, in lnlike
    res, sigma = residual(pars)
  File "lf_fitter.py", line 94, in residual
    get_fit_data(alldata,parameters,zmins[key],zmaxs[key],key,dset_ids[key])
  File "lf_fitter.py", line 38, in get_fit_data
    L_data, PHI_data, DPHI_data = load_LF_data[dset_name](redshift)
  File "/home/xuejian/works/quasarLF/git/codes/obdata/new_load_willott10_lf_data.py", line 11, in load_willott10_lf_data
    'left', 'right', 'log_phi', 'uperr', 'lowerr', 'nqso', 'Veff', 'P'])
  File "/home/xuejian/.conda/envs/customenv/lib/python2.7/site-packages/numpy/lib/npyio.py", line 1689, in genfromtxt
    fhd = iter(np.lib._datasource.open(fname, 'rt', encoding=encoding))
  File "/home/xuejian/.conda/envs/customenv/lib/python2.7/site-packages/numpy/lib/_datasource.py", line 260, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "/home/xuejian/.conda/envs/customenv/lib/python2.7/site-packages/numpy/lib/_datasource.py", line 614, in open
    encoding=encoding, newline=newline)
MemoryError
Traceback (most recent call last):
  File "lf_fitter.py", line 129, in <module>
    pool.wait()
  File "/home/xuejian/.conda/envs/customenv/lib/python2.7/site-packages/emcee/mpi_pool.py", line 117, in wait
    result = self.function(task)
  File "/home/xuejian/.conda/envs/customenv/lib/python2.7/site-packages/emcee/ensemble.py", line 519, in __call__
    return self.f(x, *self.args, **self.kwargs)
  File "lf_fitter.py", line 112, in lnprob
    llike = lnlike(pars)
  File "lf_fitter.py", line 104, in lnlike
    res, sigma = residual(pars)
  File "lf_fitter.py", line 94, in residual
    get_fit_data(alldata,parameters,zmins[key],zmaxs[key],key,dset_ids[key])
  File "lf_fitter.py", line 38, in get_fit_data
    L_data, PHI_data, DPHI_data = load_LF_data[dset_name](redshift)
  File "/home/xuejian/works/quasarLF/git/codes/obdata/new_load_willott10_lf_data.py", line 11, in load_willott10_lf_data
    'left', 'right', 'log_phi', 'uperr', 'lowerr', 'nqso', 'Veff', 'P'])
  File "/home/xuejian/.conda/envs/customenv/lib/python2.7/site-packages/numpy/lib/npyio.py", line 1689, in genfromtxt
    fhd = iter(np.lib._datasource.open(fname, 'rt', encoding=encoding))
  File "/home/xuejian/.conda/envs/customenv/lib/python2.7/site-packages/numpy/lib/_datasource.py", line 260, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "/home/xuejian/.conda/envs/customenv/lib/python2.7/site-packages/numpy/lib/_datasource.py", line 614, in open
    encoding=encoding, newline=newline)
MemoryError
Traceback (most recent call last):
  File "/home/xuejian/.conda/envs/customenv/lib/python2.7/site-packages/emcee/ensemble.py", line 519, in __call__
    return self.f(x, *self.args, **self.kwargs)
  File "lf_fitter.py", line 112, in lnprob
    llike = lnlike(pars)
  File "lf_fitter.py", line 104, in lnlike
    res, sigma = residual(pars)
  File "lf_fitter.py", line 94, in residual
    get_fit_data(alldata,parameters,zmins[key],zmaxs[key],key,dset_ids[key])
  File "lf_fitter.py", line 38, in get_fit_data
    L_data, PHI_data, DPHI_data = load_LF_data[dset_name](redshift)
  File "/home/xuejian/works/quasarLF/git/codes/obdata/new_load_willott10_lf_data.py", line 11, in load_willott10_lf_data
    'left', 'right', 'log_phi', 'uperr', 'lowerr', 'nqso', 'Veff', 'P'])
  File "/home/xuejian/.conda/envs/customenv/lib/python2.7/site-packages/numpy/lib/npyio.py", line 1689, in genfromtxt
    fhd = iter(np.lib._datasource.open(fname, 'rt', encoding=encoding))
  File "/home/xuejian/.conda/envs/customenv/lib/python2.7/site-packages/numpy/lib/_datasource.py", line 260, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "/home/xuejian/.conda/envs/customenv/lib/python2.7/site-packages/numpy/lib/_datasource.py", line 614, in open
    encoding=encoding, newline=newline)
MemoryError
Traceback (most recent call last):
  File "lf_fitter.py", line 129, in <module>
    pool.wait()
  File "/home/xuejian/.conda/envs/customenv/lib/python2.7/site-packages/emcee/mpi_pool.py", line 117, in wait
    result = self.function(task)
  File "/home/xuejian/.conda/envs/customenv/lib/python2.7/site-packages/emcee/ensemble.py", line 519, in __call__
    return self.f(x, *self.args, **self.kwargs)
  File "lf_fitter.py", line 112, in lnprob
    llike = lnlike(pars)
  File "lf_fitter.py", line 104, in lnlike
    res, sigma = residual(pars)
  File "lf_fitter.py", line 94, in residual
    get_fit_data(alldata,parameters,zmins[key],zmaxs[key],key,dset_ids[key])
  File "lf_fitter.py", line 38, in get_fit_data
    L_data, PHI_data, DPHI_data = load_LF_data[dset_name](redshift)
  File "/home/xuejian/works/quasarLF/git/codes/obdata/new_load_willott10_lf_data.py", line 11, in load_willott10_lf_data
    'left', 'right', 'log_phi', 'uperr', 'lowerr', 'nqso', 'Veff', 'P'])
  File "/home/xuejian/.conda/envs/customenv/lib/python2.7/site-packages/numpy/lib/npyio.py", line 1689, in genfromtxt
    fhd = iter(np.lib._datasource.open(fname, 'rt', encoding=encoding))
  File "/home/xuejian/.conda/envs/customenv/lib/python2.7/site-packages/numpy/lib/_datasource.py", line 260, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "/home/xuejian/.conda/envs/customenv/lib/python2.7/site-packages/numpy/lib/_datasource.py", line 614, in open
    encoding=encoding, newline=newline)
MemoryError
Traceback (most recent call last):
  File "/home/xuejian/.conda/envs/customenv/lib/python2.7/site-packages/emcee/ensemble.py", line 519, in __call__
    return self.f(x, *self.args, **self.kwargs)
  File "lf_fitter.py", line 112, in lnprob
    llike = lnlike(pars)
  File "lf_fitter.py", line 104, in lnlike
    res, sigma = residual(pars)
  File "lf_fitter.py", line 94, in residual
    get_fit_data(alldata,parameters,zmins[key],zmaxs[key],key,dset_ids[key])
  File "lf_fitter.py", line 38, in get_fit_data
    L_data, PHI_data, DPHI_data = load_LF_data[dset_name](redshift)
  File "/home/xuejian/works/quasarLF/git/codes/obdata/load_sdss_dr3_lf_data.py", line 23, in load_sdss_dr3_lf_data
    data = np.genfromtxt(filename,names=['M_i','logphi','dphi','fill','zbar','Nqso','Ncor'],skip_header=1)
  File "/home/xuejian/.conda/envs/customenv/lib/python2.7/site-packages/numpy/lib/npyio.py", line 1689, in genfromtxt
    fhd = iter(np.lib._datasource.open(fname, 'rt', encoding=encoding))
  File "/home/xuejian/.conda/envs/customenv/lib/python2.7/site-packages/numpy/lib/_datasource.py", line 260, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "/home/xuejian/.conda/envs/customenv/lib/python2.7/site-packages/numpy/lib/_datasource.py", line 614, in open
    encoding=encoding, newline=newline)
MemoryError
Traceback (most recent call last):
  File "lf_fitter.py", line 129, in <module>
    pool.wait()
  File "/home/xuejian/.conda/envs/customenv/lib/python2.7/site-packages/emcee/mpi_pool.py", line 117, in wait
    result = self.function(task)
  File "/home/xuejian/.conda/envs/customenv/lib/python2.7/site-packages/emcee/ensemble.py", line 519, in __call__
    return self.f(x, *self.args, **self.kwargs)
  File "lf_fitter.py", line 112, in lnprob
    llike = lnlike(pars)
  File "lf_fitter.py", line 104, in lnlike
    res, sigma = residual(pars)
  File "lf_fitter.py", line 94, in residual
    get_fit_data(alldata,parameters,zmins[key],zmaxs[key],key,dset_ids[key])
  File "lf_fitter.py", line 38, in get_fit_data
    L_data, PHI_data, DPHI_data = load_LF_data[dset_name](redshift)
  File "/home/xuejian/works/quasarLF/git/codes/obdata/load_sdss_dr3_lf_data.py", line 23, in load_sdss_dr3_lf_data
    data = np.genfromtxt(filename,names=['M_i','logphi','dphi','fill','zbar','Nqso','Ncor'],skip_header=1)
  File "/home/xuejian/.conda/envs/customenv/lib/python2.7/site-packages/numpy/lib/npyio.py", line 1689, in genfromtxt
    fhd = iter(np.lib._datasource.open(fname, 'rt', encoding=encoding))
  File "/home/xuejian/.conda/envs/customenv/lib/python2.7/site-packages/numpy/lib/_datasource.py", line 260, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "/home/xuejian/.conda/envs/customenv/lib/python2.7/site-packages/numpy/lib/_datasource.py", line 614, in open
    encoding=encoding, newline=newline)
MemoryError
slurmstepd: error: *** JOB 134464 ON wheeler041 CANCELLED AT 2019-02-20T13:23:52 ***
