Traceback (most recent call last):
  File "lf_fitter.py", line 156, in <module>
    f = open("output/chain.dat", "w")
Traceback (most recent call last):
  File "lf_fitter.py", line 156, in <module>
Traceback (most recent call last):
  File "lf_fitter.py", line 156, in <module>
IOError: [Errno 116] Stale file handle: 'output/chain.dat'
Traceback (most recent call last):
  File "lf_fitter.py", line 156, in <module>
    f = open("output/chain.dat", "w")
IOError: [Errno 116] Stale file handle: 'output/chain.dat'
    f = open("output/chain.dat", "w")
IOError: [Errno 116] Stale file handle: 'output/chain.dat'
Traceback (most recent call last):
  File "lf_fitter.py", line 156, in <module>
    f = open("output/chain.dat", "w")
    f = open("output/chain.dat", "w")
IOError: [Errno 116] Stale file handle: 'output/chain.dat'
IOError: [Errno 116] Stale file handle: 'output/chain.dat'
Traceback (most recent call last):
  File "lf_fitter.py", line 156, in <module>
Traceback (most recent call last):
  File "lf_fitter.py", line 156, in <module>
    f = open("output/chain.dat", "w")
    f = open("output/chain.dat", "w")
IOError: [Errno 116] Stale file handle: 'output/chain.dat'
IOError: [Errno 116] Stale file handle: 'output/chain.dat'
Traceback (most recent call last):
  File "lf_fitter.py", line 156, in <module>
    f = open("output/chain.dat", "w")
IOError: [Errno 116] Stale file handle: 'output/chain.dat'
Traceback (most recent call last):
  File "lf_fitter.py", line 156, in <module>
    f = open("output/chain.dat", "w")
IOError: [Errno 116] Stale file handle: 'output/chain.dat'
Traceback (most recent call last):
  File "lf_fitter.py", line 156, in <module>
Traceback (most recent call last):
  File "lf_fitter.py", line 156, in <module>
    f = open("output/chain.dat", "w")
    f = open("output/chain.dat", "w")
IOError: [Errno 116] Stale file handle: 'output/chain.dat'
IOError: [Errno 116] Stale file handle: 'output/chain.dat'
Traceback (most recent call last):
  File "lf_fitter.py", line 156, in <module>
    f = open("output/chain.dat", "w")
IOError: [Errno 116] Stale file handle: 'output/chain.dat'
Traceback (most recent call last):
  File "lf_fitter.py", line 156, in <module>
Traceback (most recent call last):
  File "lf_fitter.py", line 156, in <module>
Traceback (most recent call last):
  File "lf_fitter.py", line 156, in <module>
Traceback (most recent call last):
  File "lf_fitter.py", line 156, in <module>
    f = open("output/chain.dat", "w")
IOError: [Errno 116] Stale file handle: 'output/chain.dat'
    f = open("output/chain.dat", "w")
IOError: [Errno 116] Stale file handle: 'output/chain.dat'
    f = open("output/chain.dat", "w")
IOError: [Errno 116] Stale file handle: 'output/chain.dat'
    f = open("output/chain.dat", "w")
IOError: [Errno 116] Stale file handle: 'output/chain.dat'
Traceback (most recent call last):
  File "lf_fitter.py", line 156, in <module>
Traceback (most recent call last):
  File "lf_fitter.py", line 156, in <module>
    f = open("output/chain.dat", "w")
IOError: [Errno 116] Stale file handle: 'output/chain.dat'
    f = open("output/chain.dat", "w")
IOError: [Errno 116] Stale file handle: 'output/chain.dat'
Traceback (most recent call last):
  File "lf_fitter.py", line 156, in <module>
Traceback (most recent call last):
  File "lf_fitter.py", line 156, in <module>
    f = open("output/chain.dat", "w")
IOError:     f = open("output/chain.dat", "w")
IOErrorTraceback (most recent call last):
  File "lf_fitter.py", line 156, in <module>
Traceback (most recent call last):
  File "lf_fitter.py", line 156, in <module>
Traceback (most recent call last):
  File "lf_fitter.py", line 156, in <module>
[Errno 116] Stale file handle: 'output/chain.dat'
Traceback (most recent call last):
  File "lf_fitter.py", line 156, in <module>
: [Errno 116] Stale file handle: 'output/chain.dat'
    f = open("output/chain.dat", "w")
    f = open("output/chain.dat", "w")
IOError: [Errno 116] Stale file handle: 'output/chain.dat'
Traceback (most recent call last):
  File "lf_fitter.py", line 156, in <module>
    f = open("output/chain.dat", "w")
IOError: [Errno 116] Stale file handle: 'output/chain.dat'
IOError: [Errno 116] Stale file handle: 'output/chain.dat'
    f = open("output/chain.dat", "w")
    f = open("output/chain.dat", "w")
IOError: [Errno 116] Stale file handle: 'output/chain.dat'
Traceback (most recent call last):
  File "lf_fitter.py", line 156, in <module>
IOError: [Errno 116] Stale file handle: 'output/chain.dat'
Traceback (most recent call last):
  File "lf_fitter.py", line 156, in <module>
    f = open("output/chain.dat", "w")
Traceback (most recent call last):
  File "lf_fitter.py", line 156, in <module>
IOError: [Errno 116] Stale file handle: 'output/chain.dat'
Traceback (most recent call last):
  File "lf_fitter.py", line 156, in <module>
    f = open("output/chain.dat", "w")
IOError: [Errno 116] Stale file handle: 'output/chain.dat'
    f = open("output/chain.dat", "w")
    f = open("output/chain.dat", "w")
IOError: [Errno 116] Stale file handle: 'output/chain.dat'
IOError: [Errno 116] Stale file handle: 'output/chain.dat'
Traceback (most recent call last):
  File "lf_fitter.py", line 156, in <module>
    f = open("output/chain.dat", "w")
IOError: [Errno 116] Stale file handle: 'output/chain.dat'
/home/xuejian/works/quasarLF/git/codes/lf_fit/lf_shape.py:10: RuntimeWarning: overflow encountered in power
  P_temp = np.power(10.,P0) / ( np.power(x,gamma1) + np.power(x,gamma2) )
/home/xuejian/works/quasarLF/git/codes/lf_fit/lf_shape.py:11: RuntimeWarning: divide by zero encountered in log10
  P_temp = np.log10(P_temp)
/home/xuejian/works/quasarLF/git/codes/lf_fit/lf_shape.py:10: RuntimeWarning: overflow encountered in power
  P_temp = np.power(10.,P0) / ( np.power(x,gamma1) + np.power(x,gamma2) )
/home/xuejian/works/quasarLF/git/codes/lf_fit/lf_shape.py:11: RuntimeWarning: divide by zero encountered in log10
  P_temp = np.log10(P_temp)
/home/xuejian/works/quasarLF/git/codes/lf_fit/lf_shape.py:10: RuntimeWarning: overflow encountered in power
  P_temp = np.power(10.,P0) / ( np.power(x,gamma1) + np.power(x,gamma2) )
/home/xuejian/works/quasarLF/git/codes/lf_fit/lf_shape.py:11: RuntimeWarning: divide by zero encountered in log10
  P_temp = np.log10(P_temp)
/home/xuejian/works/quasarLF/git/codes/lf_fit/lf_shape.py:10: RuntimeWarning: overflow encountered in power
  P_temp = np.power(10.,P0) / ( np.power(x,gamma1) + np.power(x,gamma2) )
/home/xuejian/works/quasarLF/git/codes/lf_fit/lf_shape.py:11: RuntimeWarning: divide by zero encountered in log10
  P_temp = np.log10(P_temp)
/home/xuejian/works/quasarLF/git/codes/lf_fit/lf_shape.py:10: RuntimeWarning: overflow encountered in power
  P_temp = np.power(10.,P0) / ( np.power(x,gamma1) + np.power(x,gamma2) )
/home/xuejian/works/quasarLF/git/codes/lf_fit/lf_shape.py:11: RuntimeWarning: divide by zero encountered in log10
  P_temp = np.log10(P_temp)
/home/xuejian/works/quasarLF/git/codes/lf_fit/lf_shape.py:10: RuntimeWarning: overflow encountered in power
  P_temp = np.power(10.,P0) / ( np.power(x,gamma1) + np.power(x,gamma2) )
/home/xuejian/works/quasarLF/git/codes/lf_fit/lf_shape.py:11: RuntimeWarning: divide by zero encountered in log10
  P_temp = np.log10(P_temp)
/home/xuejian/works/quasarLF/git/codes/lf_fit/lf_shape.py:10: RuntimeWarning: overflow encountered in power
  P_temp = np.power(10.,P0) / ( np.power(x,gamma1) + np.power(x,gamma2) )
/home/xuejian/works/quasarLF/git/codes/lf_fit/lf_shape.py:11: RuntimeWarning: divide by zero encountered in log10
  P_temp = np.log10(P_temp)
/home/xuejian/works/quasarLF/git/codes/lf_fit/lf_shape.py:10: RuntimeWarning: overflow encountered in power
  P_temp = np.power(10.,P0) / ( np.power(x,gamma1) + np.power(x,gamma2) )
/home/xuejian/works/quasarLF/git/codes/lf_fit/lf_shape.py:11: RuntimeWarning: divide by zero encountered in log10
  P_temp = np.log10(P_temp)
/home/xuejian/works/quasarLF/git/codes/lf_fit/lf_shape.py:10: RuntimeWarning: overflow encountered in power
  P_temp = np.power(10.,P0) / ( np.power(x,gamma1) + np.power(x,gamma2) )
/home/xuejian/works/quasarLF/git/codes/lf_fit/lf_shape.py:11: RuntimeWarning: divide by zero encountered in log10
  P_temp = np.log10(P_temp)
/home/xuejian/works/quasarLF/git/codes/lf_fit/lf_shape.py:10: RuntimeWarning: overflow encountered in power
  P_temp = np.power(10.,P0) / ( np.power(x,gamma1) + np.power(x,gamma2) )
/home/xuejian/works/quasarLF/git/codes/lf_fit/lf_shape.py:11: RuntimeWarning: divide by zero encountered in log10
  P_temp = np.log10(P_temp)
slurmstepd: error: *** JOB 181528 ON wheeler030 CANCELLED AT 2019-06-23T16:27:10 DUE TO TIME LIMIT ***
